version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    env_file:
      - .env.prod
    volumes:
      - postgres_volume_test:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ms_network

  api:
    container_name: api
    build:
      context: ./app
      target: production
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    volumes:
      - .:/hotel
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - db
    restart: always
    networks:
      - ms_network

volumes:
  postgres_volume_test:

networks:
  ms_network:
#    external: true
